---
# tasks file for cloud-backup-agent
- name: Debian | Supported OS
  set_fact:
    cloud_backup_agent_supported_os: True

- name: setup backup agent apt key
  apt_key: url='http://agentrepo.drivesrvr.com/debian/agentrepo.key' state=present

- name: setup backup agent apt repository
  apt_repository: repo='deb [arch=amd64] http://agentrepo.drivesrvr.com/debian/ serveragent main' state=present

- name: install backup agent
  apt: name=driveclient state=present update_cache=yes cache_valid_time=86400

- name: remove extra apt source
  file: path=/etc/apt/sources.list.d/driveclient.list state=absent
