---
# tasks file for cloud-backup-agent
- name: setup backup agent apt key
  apt_key: url='http://agentrepo.drivesrvr.com/debian/agentrepo.key' state=present

- name: setup backup agent apt repository
  apt_repository: repo='deb [arch=amd64] http://agentrepo.drivesrvr.com/debian/ serveragent main' state=present

- name: install backup agent
  apt: name=driveclient state=present update_cache=yes cache_valid_time=86400

- name: setup the backup agent
  command: driveclient --configure --username {{ rackspace_username }} --apikey {{ rackspace_apikey }} creates=/etc/driveclient/bootstrap.json

- name: ensure agent is started
  service: name=driveclient state=started
