---
# tasks file for cloud-backup-agent
- name: RedHat | Supported OS
  set_fact:
    cloud_backup_agent_supported_os: True

- name: setup backup agent yum repo
  template: src=RedHat.repo dest=/etc/yum.repos.d/drivesrvr.repo owner=root group=root mode=0644

- name: install backup agent
  yum: name=driveclient state=present
